services:
  - type: web
    name: dog-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /health
    autoDeploy: true 